### ISSUE TITLE
Broken Documentation Link

### ISSUE THREAD

**Issue by RyanNorge** [petabyt/camlib#11]
The link to the documentation in your readme.md is broken.
Right now it goes to...
https://danielc.dev/camlib-docs/

Poking around a bit on your site, I think maybe it's supposed to go to...
https://danielc.dev/camlib/

And also, python bindings would be great for people like me who suck at computers :)

**Comment by petabyt** [comment]
Sorry about that, been busy lately, will fix it. For Python, I recommend ptpy. That's what I started with when hacking cameras and it still holds up well today. There's also https://github.com/lclevy/miniPtp which is also actively maintained by a ML dev.

**Comment by RyanNorge** [comment]
Wonderful, thanks for the tips. I was a bit skeptical about ptpy because it's not maintained, but if you recommend it I'll check it out :)
