### ISSUE TITLE
project as a dll

### ISSUE THREAD

**Issue by maxm74** [petabyt/camlib#12]
In order to use this library in other languages ​​it should also be compiled as a dll. 
Can I make two visualstudio projects (one using libusb and the other using libwpd)? 
I would like to use it in freepascal. 

Thanks.

**Comment by petabyt** [comment]
I use mingw and compile an archive for static linking. Most compilers should accept that. I don't know how you are going to use it in Pascal, you would have to write a bunch of bindings yourself.

**Comment by maxm74** [comment]
You can link statically as long as you use C or C++, to use it with other languages ​​it has to be a dynamic library. So I would only have to translate the types, constants, and function definitions. I will fork the repository and make a merge request these days if you agree.

**Comment by petabyt** [comment]
Rust/Zig and other LLVM-based languages are capable of accepting clang archives. I know nothing about Pascal compilers. I can easily add a target for mingw/Linux dll/so but this library is not stable and I haven't created a stable release yet. There will be early adopter pains.
