### ISSUE TITLE
Cannot build on Linux or Windows

### ISSUE THREAD

**Issue by laheller** [petabyt/camlib#4]
Hi @petabyt @etra0  !

When I try to build I receive following error:

> $ make
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/operations.c -o src/operations.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/packet.c -o src/packet.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/enums.c -o src/enums.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/data.c -o src/data.o
> cd src && python3 stringify.py
> Compiled 340 enums
> cc -c src/enum_dump.c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g -o src/enum_dump.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/util.c -o src/util.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/canon.c -o src/canon.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/liveview.c -o src/liveview.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/bind.c -o src/bind.o
> cc -c -I/usr/include/libusb-1.0 -lusb-1.0 -Isrc/ -I../mjs/ -DVERBOSE -Wall -g src/libusb.c -o src/libusb.o
> src/libusb.c: In function ‘ptp_device_init’:
> src/libusb.c:83:43: error: ‘LIBUSB_ENDPOINT_TRANSFER_TYPE_BULK’ undeclared (first use in this function); did you mean ‘LIBUSB_TRANSFER_TYPE_BULK’?
>    83 |                 if (ep[i].bmAttributes == LIBUSB_ENDPOINT_TRANSFER_TYPE_BULK) {
>       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                           LIBUSB_TRANSFER_TYPE_BULK
> src/libusb.c:83:43: note: each undeclared identifier is reported only once for each function it appears in
> src/libusb.c:91:50: error: ‘LIBUSB_ENDPOINT_TRANSFER_TYPE_INTERRUPT’ undeclared (first use in this function); did you mean ‘LIBUSB_TRANSFER_TYPE_INTERRUPT’?
>    91 |                 } else if (ep[i].bmAttributes == LIBUSB_ENDPOINT_TRANSFER_TYPE_INTERRUPT) {
>       |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                                  LIBUSB_TRANSFER_TYPE_INTERRUPT
> make: *** [Makefile:28: src/libusb.o] Error 1
> 

Any tips?

BR,

Ladislav

**Comment by petabyt** [comment]
Weird, LIBUSB_ENDPOINT_TRANSFER_TYPE_INTERRUPT should be defined in the latest libusb spec. Make sure you have the latest version.

**Comment by laheller** [comment]
> Weird, LIBUSB_ENDPOINT_TRANSFER_TYPE_INTERRUPT should be defined in the latest libusb spec. Make sure you have the latest version.

@petabyt 
Is this the latest:
https://github.com/libusb/libusb
?

**Comment by petabyt** [comment]
Any 1.0 version since 2008 should work fine

**Comment by etra0** [comment]
In linux, make sure you have the development dependencies, in the case of Debian flavors (Ubuntu too), you should install `libusb-1.0-0-dev` (`sudo apt install libusb-1.0-0-dev`).

**Comment by laheller** [comment]
@petabyt  @etra0 

OK, now I was able to build, but...
... no static/shared library (.so OR .a) as output?
At least I was not able to find them.

![image](https://user-images.githubusercontent.com/5788998/231390567-34e5551e-06d7-4aac-a488-2c8ef22eb35c.png)

**Comment by petabyt** [comment]
The makefile doesn't compile a shared library

**Comment by laheller** [comment]
> The makefile doesn't compile a shared library

@petabyt 
Neither a static library, apparently...

Can U please update the makefile to perform also a library creation?

**Comment by petabyt** [comment]
Might add it in the near future, but generally camlib is intended to be portable enough to be compiled directly into applications
