### ISSUE TITLE
Segfault on "bind_run"

### ISSUE THREAD

**Issue by laheller** [petabyt/camlib#8]
Hi!

@petabyt 

I am trying the following code:
```
#include <stdio.h>
#include <camlib.h>

int main(int argc, char** argv) {
    struct PtpRuntime ptp;
    ptp_generic_init(&ptp);

    char buffer[PTP_BIND_DEFAULT_SIZE];
    int r = bind_run(&ptp, "ptp_init", buffer, sizeof(buffer));
    printf("ptp_init: %s\n", buffer);

    r = bind_run(&ptp, "ptp_connect", buffer, sizeof(buffer));
    printf("ptp_connect: %s\n", buffer);

    r = bind_run(&ptp, "ptp_open_session", buffer, sizeof(buffer));
    printf("ptp_open_session: %s\n", buffer);

    r = bind_run(&ptp, "ptp_get_device_info", buffer, sizeof(buffer));
    printf("ptp_get_device_info: %s\n", buffer);

    r = bind_run(&ptp, "ptp_close_session", buffer, sizeof(buffer));
    printf("ptp_close_session: %s\n", buffer);

    r = bind_run(&ptp, "ptp_disconnect", buffer, sizeof(buffer));
    printf("ptp_disconnect: %s\n", buffer);

    ptp_generic_close(&ptp);
}

```

Which unfortunately ends up with segmentation fault on **ptp_get_device_info**:

> **ptp_init**: {"error": 0, "buffer": 8000000}
> Initializing USB...
> Vendor ID: 4A9, Product ID: 32B4
> Endpoint IN addr: 0x81
> Endpoint OUT addr: 0x2
> Endpoint INT addr: 0x83
> **ptp_connect**: {"error": 0}
> send_bulk_packets 0x1002 (PTP_OC_OpenSession)
> send_bulk_packet: Sent 16 bytes
> recieve_bulk_packets: Read 12 bytes
> recieve_bulk_packets: Return code: 0x2001
> **ptp_open_session**: {"error": 0}
> Segmentation fault
> 

Any idea, where is the problem? Did I maybe miss something?

BR,

Ladislav

**Comment by petabyt** [comment]
My latest few changes have some broken mutex code. I'll be fixing it very soon.

**Comment by petabyt** [comment]
Actually, your problem seems to be with calling `ptp_generic_init` and then `bind_init`, which do the same thing.
Getting rid of:
```
char buffer[PTP_BIND_DEFAULT_SIZE];
int rc = bind_run(&r, "ptp_init", buffer, sizeof(buffer));
printf("ptp_init: %s\n", buffer);
```
Would fix it. Although I'm gonna push a fix that prevents a segfault. (but would leak memory in your example)

**Comment by petabyt** [comment]
https://github.com/petabyt/camlib/commit/5a05ce3f6df058d48d3659db6cf690985e9ce32c should have fixed it

**Comment by laheller** [comment]
@petabyt 
Sorry for late response, yes, now it works.
